// flow-typed signature: 982a20864b4dcea9e8fa787e037a8364
// flow-typed version: <<STUB>>/babel-preset-power-assert_v3.0.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-power-assert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-power-assert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-power-assert/index' {
  declare module.exports: $Exports<'babel-preset-power-assert'>;
}
declare module 'babel-preset-power-assert/index.js' {
  declare module.exports: $Exports<'babel-preset-power-assert'>;
}
